### PR TITLE
Gnome 47 testing

### PR DESCRIPTION
**Pull request by Schmiddiii**
See also https://github.com/flathub/de.schmidhuberj.tubefeeder/pull/37#issuecomment-2365168900.

### CODE REVIEW

**Comment by Schmiddiii** [comment]
Lima Kernel logs from `journalctl --grep lima`:

```
Sep 24 15:16:17 danctnix kernel: lima 1c40000.gpu: gp - mali400 version major 1 minor 1
Sep 24 15:16:17 danctnix kernel: lima 1c40000.gpu: pp0 - mali400 version major 1 minor 1
Sep 24 15:16:17 danctnix kernel: lima 1c40000.gpu: pp1 - mali400 version major 1 minor 1
Sep 24 15:16:17 danctnix kernel: lima 1c40000.gpu: l2_cache0 64K, 4-way, 64byte cache line, 64bit external bus
Sep 24 15:16:17 danctnix kernel: lima 1c40000.gpu: bus rate = 200000000
Sep 24 15:16:17 danctnix kernel: lima 1c40000.gpu: mod rate = 297000000
Sep 24 15:16:17 danctnix kernel: lima 1c40000.gpu: Failed to register cooling device
Sep 24 15:16:17 danctnix kernel: [drm] Initialized lima 1.1.0 20191231 for 1c40000.gpu on minor 1
Sep 24 15:20:30 danctnix kernel: lima 1c40000.gpu: ppmmu0 page fault at 0xc297200 from bus id 0 of type read
Sep 24 15:20:30 danctnix kernel: lima 1c40000.gpu: ppmmu1 page fault at 0xc297000 from bus id 0 of type read
Sep 24 15:20:30 danctnix kernel: lima 1c40000.gpu: pp0 task error 0 int_state=0 status=1
Sep 24 15:20:30 danctnix kernel: lima 1c40000.gpu: pp0 bus stop timeout
Sep 24 15:20:30 danctnix kernel: lima 1c40000.gpu: pp1 task error 1 int_state=0 status=1
Sep 24 15:20:30 danctnix kernel: lima 1c40000.gpu: pp1 bus stop timeout
Sep 24 15:20:30 danctnix kernel: lima 1c40000.gpu: ppmmu0 resume
Sep 24 15:20:30 danctnix kernel: lima 1c40000.gpu: ppmmu1 resume
Sep 24 15:20:40 danctnix kernel: [drm:lima_sched_timedout_job [lima]] *ERROR* pp0 job timeout
Sep 24 15:20:40 danctnix kernel: lima 1c40000.gpu: pp0 task error 0 int_state=0 status=5
Sep 24 15:20:40 danctnix kernel: lima 1c40000.gpu: pp0 bus stop timeout
Sep 24 15:20:40 danctnix kernel: lima 1c40000.gpu: pp1 task error 1 int_state=0 status=5
Sep 24 15:20:40 danctnix kernel: lima 1c40000.gpu: pp1 bus stop timeout
Sep 24 15:20:50 danctnix kernel: [drm:lima_sched_timedout_job [lima]] *ERROR* pp0 job timeout
Sep 24 15:20:50 danctnix kernel: lima 1c40000.gpu: pp0 task error 0 int_state=0 status=5
Sep 24 15:20:50 danctnix kernel: lima 1c40000.gpu: pp0 bus stop timeout
Sep 24 15:20:50 danctnix kernel: lima 1c40000.gpu: pp1 task error 1 int_state=0 status=5
Sep 24 15:20:50 danctnix kernel: lima 1c40000.gpu: pp1 bus stop timeout
Sep 24 15:21:01 danctnix kernel: [drm:lima_sched_timedout_job [lima]] *ERROR* pp0 job timeout
Sep 24 15:21:01 danctnix kernel: lima 1c40000.gpu: pp0 task error 0 int_state=0 status=5
Sep 24 15:21:01 danctnix kernel: lima 1c40000.gpu: pp0 bus stop timeout
Sep 24 15:21:01 danctnix kernel: lima 1c40000.gpu: pp1 task error 1 int_state=0 status=5
Sep 24 15:21:01 danctnix kernel: lima 1c40000.gpu: pp1 bus stop timeout
Sep 24 15:21:11 danctnix kernel: [drm:lima_sched_timedout_job [lima]] *ERROR* pp0 job timeout
Sep 24 15:21:11 danctnix kernel: lima 1c40000.gpu: pp0 task error 0 int_state=0 status=5
Sep 24 15:21:11 danctnix kernel: lima 1c40000.gpu: pp0 bus stop timeout
Sep 24 15:21:11 danctnix kernel: lima 1c40000.gpu: pp1 task error 1 int_state=0 status=5
Sep 24 15:21:11 danctnix kernel: lima 1c40000.gpu: pp1 bus stop timeout
Sep 24 15:21:21 danctnix kernel: [drm:lima_sched_timedout_job [lima]] *ERROR* pp0 job timeout
Sep 24 15:21:21 danctnix kernel: lima 1c40000.gpu: pp0 task error 0 int_state=0 status=5
Sep 24 15:21:21 danctnix kernel: lima 1c40000.gpu: pp0 bus stop timeout
Sep 24 15:21:21 danctnix kernel: lima 1c40000.gpu: pp1 task error 1 int_state=0 status=5
Sep 24 15:21:21 danctnix kernel: lima 1c40000.gpu: pp1 bus stop timeout
Sep 24 15:21:31 danctnix kernel: [drm:lima_sched_timedout_job [lima]] *ERROR* pp0 job timeout
Sep 24 15:21:31 danctnix kernel: lima 1c40000.gpu: pp0 task error 0 int_state=0 status=5
Sep 24 15:21:31 danctnix kernel: lima 1c40000.gpu: pp0 bus stop timeout
Sep 24 15:21:31 danctnix kernel: lima 1c40000.gpu: pp1 task error 1 int_state=0 status=5
Sep 24 15:21:31 danctnix kernel: lima 1c40000.gpu: pp1 bus stop timeout
Sep 24 15:21:42 danctnix kernel: [drm:lima_sched_timedout_job [lima]] *ERROR* pp0 job timeout
Sep 24 15:21:42 danctnix kernel: lima 1c40000.gpu: pp0 task error 0 int_state=0 status=5
Sep 24 15:21:42 danctnix kernel: lima 1c40000.gpu: pp0 bus stop timeout
Sep 24 15:21:42 danctnix kernel: lima 1c40000.gpu: pp1 task error 1 int_state=0 status=5
Sep 24 15:21:42 danctnix kernel: lima 1c40000.gpu: pp1 bus stop timeout
Sep 24 15:21:52 danctnix kernel: [drm:lima_sched_timedout_job [lima]] *ERROR* pp0 job timeout
Sep 24 15:21:52 danctnix kernel: lima 1c40000.gpu: pp0 task error 0 int_state=0 status=5
Sep 24 15:21:52 danctnix kernel: lima 1c40000.gpu: pp0 bus stop timeout
Sep 24 15:21:52 danctnix kernel: lima 1c40000.gpu: pp1 task error 1 int_state=0 status=5
Sep 24 15:21:52 danctnix kernel: lima 1c40000.gpu: pp1 bus stop timeout
```

**Comment by agx** [comment]
I'm not very familiar with lima but

```
Sep 24 15:21:21 danctnix kernel: [drm:lima_sched_timedout_job [lima]] *ERROR* pp0 job timeout
```

looks suspicious (and is pretty likely the reason why the whole system "locks up"). As unprivileged userspace should't be able to do this it's at least an issue in kernel/mesa? 

Did mesa change between the working and non-working flatpak too?

**Comment by Schmiddiii** [comment]
> and is pretty likely the reason why the whole system "locks up"

That could be the reason, but I also have no idea how that happens in the first place.

> Did mesa change between the working and non-working flatpak too?

The only change to this Flatpak is updated GNOME runtime to 47, ffmpeg to 24.08 and a permission change to allow hardware decoding in the first place.
I don't know here mesa is included in the stack, but the distribution outside the Flatpak did not update.

**Comment by agx** [comment]
Mesa comes via the FDO runtime. `org.freedesktop.Platform.GL.default` and `org.freedesktop.Platform` remained unchanged?

**Comment by Schmiddiii** [comment]
I did not update it myself, so (unless it changes between `org.gnome.Platform`, it remained unchanged.

**Comment by agx** [comment]
> I did not update it myself, so (unless it changes between org.gnome.Platform, it remained unchanged.

I think:

flatpak info --show-metadata org.gnome.Platform/x86_64/46 | grep -a1  org.freedesktop.Platform.GL]

flatpak info --show-metadata org.gnome.Platform/x86_64/47 | grep -a1  org.freedesktop.Platform.GL]

(or aarch64 if your're on the PP) should tell you if it's using the same mesa. I'm not much of a flatpak person.

**Comment by Rafostar** [comment]
Simply `flatpak list` should give you version info:
```sh
Mesa    org.freedesktop.Platform.GL.default        24.2.3        24.08       flathub    system
```

On an up-to-date system should be `mesa-24.2.3` since (as far as I see) it was updated to this exact same version in 23.08 and 24.08 runtimes few days ago (and release tagged yesterday):

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commit/c1e684aeebf93795195f2abdc77c30e66a3bf03a

FWIW, previous (pre-yesterday) release of 23.08 had `24.2.1` and same goes for first release of 24.08.
You should be able to downgrade 24.08 to mesa `24.2.1` if you go from 24.08.2 -> 24.08.0.

**Comment by rmader** [comment]
@Schmiddiii one thing you could check for your device is whether you have enough CMA memory as the HW decoder needs that apparently:
```
pine64-pinephone:~$ cat /proc/meminfo | grep Cma
CmaTotal:         262144 kB
CmaFree:          118060 kB
```

If especially if it's `0` that would be a hint.

**Comment by Schmiddiii** [comment]
@Rafostar both upgrading to 24.2.3 (I was at 24.2.1 or .2) and downgrading to 24.2.0 did not help.

@rmader seems like I got the same CMA memory as you do. Can you reproduce the issue on your PinePhone with the build on this branch?

**Comment by rmader** [comment]
> @rmader seems like I got the same CMA memory as you do. Can you reproduce the issue on your PinePhone with the build on this branch?

Gave it a very quick try - I use pmOS on my PP - and indeed I get a driver freeze after a couple of seconds :)
And the same doesn't happen on 46

**Comment by Rafostar** [comment]
@rmader 

> check for your device is whether you have enough CMA memory as the HW decoder needs that apparently
> (...)
> and indeed I get a driver freeze after a couple of seconds :)
> And the same doesn't happen on 46

Please note that Pipeline Flatpak 46 build only has software decoding and in 47 the same issue happens with either software or v4l2 stateless decoder (OP tried both), so its not HW decoding that causes driver to crash.

**Comment by agx** [comment]
Maybe as a data point: mesa 24.2.{2,3}  / gst 1.24.8 / gtk 4.16.2 work on PP here when playing videos with livi. I'll see if I can get pipeline built to test against that same set (will be a moment on the PP :smile:)

**Comment by agx** [comment]
…so building locally worked but when I want to play video the GUI complains about a missing plugin for `text/html` decoder :smile:  so I assume gstreamer gets presented the raw html page. Anything I'm missing here?

Is there a way to exercise the video playback by passing a local video?

**Comment by agx** [comment]
@Schmiddiii what kernel versions are you using? https://gitlab.com/postmarketOS/pmaports/-/issues/805#note_2002179891 indicates it should be at least 6.10 (the issue described there triggers more often when accessing the  network which could be the case when streaming videos :smile:)

**Comment by Schmiddiii** [comment]
I just tested video playback with NewsFlash and the [GNOME 47 update MR](https://github.com/flathub/io.gitlab.news_flash.NewsFlash/pull/25) and have the same issue. I will try totest if that issue also happens with only Clapper and not included into another app [here](https://github.com/flathub/com.github.rafostar.Clapper/pull/29).

**Comment by Schmiddiii** [comment]
bot, build

**Comment by Schmiddiii** [comment]
Closing in favor of #37.

**Pull request closed without merging**
